# Generated by Django 3.1.7 on 2021-08-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam42_babel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highscore',
            name='userCode',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
