# Generated by Django 3.1.7 on 2021-08-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam42_babel', '0003_auto_20210829_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='userCode',
            field=models.CharField(max_length=12),
        ),
    ]
