# Generated by Django 3.1.7 on 2021-10-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam42_babel', '0005_auto_20211021_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='highscore',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
    ]
