# Generated by Django 3.1.7 on 2021-10-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam42_babel', '0006_highscore_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='userCode',
            field=models.CharField(max_length=99),
        ),
    ]
