# Generated by Django 3.1.7 on 2021-05-29 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('salt', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=256)),
                ('money', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Yoyocoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('basevalue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('targetvalue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shares', models.IntegerField()),
                ('baseshares', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('stock', models.CharField(default='yoyo', max_length=64)),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoyocoin.investor')),
            ],
        ),
    ]
