# Generated by Django 3.1.7 on 2021-05-29 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoyocoin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yoyocoin',
            name='baseshares',
        ),
    ]
