# Generated by Django 3.1.7 on 2021-05-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyocoin', '0002_remove_yoyocoin_baseshares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('title', models.CharField(max_length=64)),
                ('clip', models.CharField(max_length=256)),
                ('valueChange', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
