# Generated by Django 3.1.7 on 2021-05-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyocoin', '0004_auto_20210531_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='baseshares',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
        ),
    ]
