# Generated by Django 3.1.7 on 2021-06-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyocoin', '0005_company_baseshares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='baseshares',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=24),
        ),
        migrations.AlterField(
            model_name='company',
            name='shares',
            field=models.DecimalField(decimal_places=2, max_digits=24),
        ),
        migrations.AlterField(
            model_name='investor',
            name='money',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=24),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=24),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=24),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='valueChange',
            field=models.DecimalField(decimal_places=2, max_digits=24),
        ),
        migrations.AlterField(
            model_name='value',
            name='basevalue',
            field=models.DecimalField(decimal_places=2, max_digits=24),
        ),
        migrations.AlterField(
            model_name='value',
            name='targetvalue',
            field=models.DecimalField(decimal_places=2, max_digits=24),
        ),
        migrations.AlterField(
            model_name='value',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=24),
        ),
    ]
