# Generated by Django 3.1.7 on 2021-06-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyocoin', '0008_auto_20210612_2349'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['time'], name='yoyocoin_va_time_d0c2d5_idx'),
        ),
    ]
