# Generated by Django 3.1.7 on 2021-06-13 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yoyocoin', '0009_auto_20210613_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
