# Generated by Django 4.2.1 on 2023-06-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='highScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('score', models.IntegerField()),
                ('uid', models.CharField(max_length=99)),
                ('date', models.DateTimeField(auto_now=True)),
                ('run', models.CharField(max_length=1024)),
                ('hash', models.CharField(max_length=128)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='get_away_fr_date_c542c1_idx'), models.Index(fields=['score'], name='get_away_fr_score_290f92_idx')],
            },
        ),
    ]
